version: '2'

services:
  web:
    build: .
    ports:
      - "8000:8000"
  fpm:
    image: phpfpm

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
    - "8000:80"
    volumes:
    - /vagrant/web:/usr/share/nginx/html:ro
    links:
      - php

      # - ./src:/var/www
      #    - ./simple_conf/sites-available/example.com.conf:/ect/nginx/nginx.conf:ro
#   - ./simple_conf/nginx.conf:/etc/nginx/nginx.conf:ro - IF CHANGING CONFIG

#   - ./var/log/nginx:/var/log/nginx - REMOVE # IF LOGGING


